// Builds /kz/ and /en/ copies of index.html and privacy.html from the Russian source.
// Run after any change to the Russian pages or to i18n/pages.mjs:  npm run i18n
// Fails when a Russian fragment from i18n/pages.mjs no longer exists in the source,
// and warns about Russian text left untranslated in the output.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as dict from '../i18n/pages.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SITE = 'https://altyn-click.pages.dev/';

const LANGS = {
  kk: {
    dir: 'kz', col: 1, og: 'kk_KZ',
    // Unbounded and Manrope lack Kazakh letters; Unbounded stays only for the Latin wordmark
    fonts: 'https://fonts.googleapis.com/css2?family=Geologica:wght@400;600;700&family=Onest:wght@400;600;700;800&family=Unbounded:wght@600&display=swap',
  },
  en: { dir: 'en', col: 2, og: 'en_US', fonts: null },
};
const OG_ALL = ['ru_RU', 'kk_KZ', 'en_US'];

// Whitespace-insensitive search: formatting of the source HTML may change without breaking the dictionary
const toRegex = s => new RegExp(s.trim().replace(/[.*+?^${}()|[\]\\]/g, '\\$&').replace(/\s+/g, '\\s+'), 'g');

function translate(html, entries, col, file) {
  const missing = [];
  const slots = [];
  // Longest fragments first; matches become placeholders so a short fragment can't hit inside a replaced one
  const sorted = [...entries].sort((a, b) => b[0].length - a[0].length);
  for (const e of sorted) {
    const re = toRegex(e[0]);
    let hit = false;
    html = html.replace(re, () => { hit = true; slots.push(e[col]); return '\u0000' + (slots.length - 1) + '\u0000'; });
    if (!hit) missing.push(e[0]);
  }
  if (missing.length) {
    console.error(`\n✖ ${file}: ${missing.length} fragment(s) from i18n/pages.mjs not found in the Russian source:`);
    missing.forEach(m => console.error('   • ' + m.slice(0, 110)));
    process.exitCode = 1;
  }
  return html.replace(/\u0000(\d+)\u0000/g, (_, i) => slots[+i]);
}

// Pages live one folder deeper, so relative asset URLs get a ../ prefix (sibling pages excluded)
const SKIP = /^(#|\/|[a-z]+:|index\.html|privacy\.html)/i;
function rebase(html) {
  html = html.replace(/\b(src|href)="([^"]*)"/g, (m, attr, url) => SKIP.test(url) || !url ? m : `${attr}="../${url}"`);
  return html.replace(/\bsrcset="([^"]*)"/g, (m, list) =>
    'srcset="' + list.split(',').map(part => {
      const p = part.trim();
      return SKIP.test(p) ? p : '../' + p;
    }).join(', ') + '"');
}

function localize(html, lang, file) {
  const L = LANGS[lang];
  const url = SITE + L.dir + '/' + (file === 'index.html' ? '' : file);
  // Source comments are Russian dev notes; the copy gets a single "generated" marker instead
  html = html.replace(/<!--[\s\S]*?-->\n?/g, '');
  html = html.replace('<html lang="ru">', `<!-- Generated by scripts/build-i18n.mjs from /${file} — edit the Russian source and i18n/, then run npm run i18n -->\n<html lang="${lang}">`);
  html = html.replace(/(<link rel="canonical" href=")[^"]*(">)/, `$1${url}$2`);
  html = html.replace(/(<meta property="og:url" content=")[^"]*(">)/, `$1${url}$2`);
  html = html.replace(/<meta property="og:locale" content="[^"]*">(\s*<meta property="og:locale:alternate" content="[^"]*">)*/,
    [`<meta property="og:locale" content="${L.og}">`, ...OG_ALL.filter(o => o !== L.og).map(o => `<meta property="og:locale:alternate" content="${o}">`)].join('\n'));
  if (L.fonts) html = html.replace(/<link href="https:\/\/fonts\.googleapis\.com\/css2\?[^"]*" rel="stylesheet">/, `<link href="${L.fonts}" rel="stylesheet">`);
  // The switcher marks the current language
  html = html.replace(/(data-lang="ru") aria-current="page"/g, '$1');
  html = html.replace(new RegExp(`(data-lang="${lang}")`, 'g'), '$1 aria-current="page"');
  html = rebase(html);
  // Runtime strings for app.js load first; both scripts are deferred, so order is kept
  html = html.replace('<script src="../app.js" defer></script>', `<script src="../i18n/${lang}.js" defer></script>\n<script src="../app.js" defer></script>`);
  return html;
}

// Text nodes of the Russian page that should not survive translation
const KEEP = new Set(['Altyn Click', 'Telegram', 'WhatsApp', 'Instagram', 'Рус', 'Қаз', 'Eng', 'Промокод', 'Портфолио', 'Стоматология', 'Дизайн', 'Процесс', 'Бриф', 'Тропинка', 'Наталья', 'Навигация', 'Алматы', '02 · Портфолио', '120 000 ₸ (база)']);
const textNodes = html => [...html.replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>|<svg[\s\S]*?<\/svg>/g, '')
  .matchAll(/>([^<>]+)</g)].map(m => m[1].replace(/\s+/g, ' ').trim()).filter(t => /[А-Яа-яЁё]{3}/.test(t) && !KEEP.has(t));

function check(src, out, lang, file) {
  const left = new Set(textNodes(out));
  const same = [...new Set(textNodes(src))].filter(t => left.has(t));
  if (same.length) {
    console.warn(`⚠ ${lang}/${file}: untranslated text:`);
    same.forEach(t => console.warn('   • ' + t.slice(0, 110)));
  }
  if (lang === 'en') {
    const cyr = [...out.matchAll(/[^<>"]*[А-Яа-яЁёӘәҒғҚқҢңӨөҰұҮүҺһІі][^<>"]*/g)].map(m => m[0].trim())
      .filter(t => !['Рус', 'Қаз'].includes(t));
    if (cyr.length) { console.warn(`⚠ en/${file}: Cyrillic left:`); cyr.forEach(t => console.warn('   • ' + t.slice(0, 110))); }
    const ruNum = out.match(/\d \d{3} ₸/g);
    if (ruNum) console.warn(`⚠ en/${file}: Russian number format left: ${ruNum.join(', ')}`);
  }
  for (const m of out.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)) {
    try { JSON.parse(m[1]); } catch (e) { console.error(`✖ ${lang}/${file}: broken JSON-LD — ${e.message}`); process.exitCode = 1; }
  }
}

for (const [file, entries] of [['index.html', dict.index], ['privacy.html', dict.privacy]]) {
  const src = readFileSync(join(ROOT, file), 'utf8');
  for (const [lang, L] of Object.entries(LANGS)) {
    const out = localize(translate(src, entries, L.col, `${lang}/${file}`), lang, file);
    check(src, out, lang, file);
    const dest = join(ROOT, L.dir, file);
    mkdirSync(dirname(dest), { recursive: true });
    writeFileSync(dest, out);
    console.log(`✓ ${L.dir}/${file}`);
  }
}
